### ISSUE TITLE
Grant Claude Code GH Actions workflow permissions to run tests and create PRs

### ISSUE THREAD

**Issue by broothie** [broothie/cob#7]
## Summary
The Claude Code GitHub Actions workflow currently lacks sufficient permissions to:
1. Run tests in the repository
2. Create pull requests automatically

## Current Limitations
Based on the recent workflow runs, Claude Code encounters permission issues when attempting to:
- Execute test commands (likely due to missing `contents: read` or `actions: read` permissions)
- Create pull requests programmatically (missing `pull-requests: write` permission)

## Requested Changes
Update the Claude Code workflow permissions to include:

```yaml
permissions:
  contents: read
  pull-requests: write
  issues: write
  actions: read
```

@claude
